### ISSUE TITLE
Improve performance of List object interface

### ISSUE THREAD

**Issue by glaubervila** [linea-it/manga#101]
Para melhorar a performance da interface "Lista de Objetos" é necessário atualizar as dependencias do frontend, o componente de data grid utilizado na epoca está extremamente desatualizado, o que está dificultando a manutenção e ainda tem o agravante de que a documentação para esta versão foi removida do site. 

Intenção dessa tarefa é reescrever essa interface usando os mesmos componentes usados em outros projetos como Pz Server, que está bem atualizado e a biblioteca parece ter um suporte melhor. mantendo disponivel documentação de versões anteriores por exemplo.  Pretendo utilizar somente o Material UI. removendo do projeto a lib @devexpress/dx-react-grid

```[tasklist]
### Tasks
- [x] Refactoring Object List
- [x] Refactoring Filter List
- [x] Refactoring Preview Component
- [ ] https://github.com/linea-it/manga/issues/123
- [ ] https://github.com/linea-it/manga/issues/124
```
