### ISSUE TITLE
Implement Pre-commit

### ISSUE THREAD

**Issue by glaubervila** [linea-it/manga#132]
```[tasklist]
### Tasks
- [ ] Implement Lint for Frontend
- [ ] Implement Formatter for Frontend
- [ ] Add Github Action CI for bump Versions on merge with master  https://github.com/commitizen-tools/commitizen-action
```
