### ISSUE TITLE
Portal version in the footer

### ISSUE THREAD

**Issue by glaubervila** [linea-it/manga#93]
Currently the portal version is hardcoded, it is necessary to implement a CI to automate the increment of versions and display the current version in the footer
```[tasklist]
### Tasks
- [x] https://github.com/linea-it/manga/issues/132
- [x] Implment Commitzen + Version Bump
- [ ] https://github.com/linea-it/manga/issues/133
```
